[mypy]
strict = True
ignore_missing_imports = True
disallow_untyped_calls = False
disable_error_code = no-any-return
explicit_package_bases = True

# Ignore type errors in the external piqe.py file
[mypy-rationai.qc.focus.piqe]
ignore_errors = True