[project]
name = "rationai-qc"
version = "1.0.1"
description = ""
authors = [
    { name = "Tomáš Balák", email = "tomasbalak@mail.muni.cz" },
    { name = "Erik Sedlák", email = "521008@mail.muni.cz" },
    { name = "Samuel Tichý", email = "524626@mail.muni.cz" },
    { name = "Karel Štěpka", email = "chuckie@mail.muni.cz" },
]
requires-python = ">=3.11"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "scikit-image>=0.24.0",
    "pyvips>=2.2.3",
    "rationai-staining",
    "opencv-python>=4.10.0.84",
    "rationai-masks",
]

[tool.uv.sources]
rationai-masks = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git" }
rationai-staining = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/staining.git", branch = "refactor/color-conversion" }

[dependency-groups]
dev = ["mypy", "pre-commit", "ruff"]
test = ["pytest", "pytest-cov"]
docs = ["mkdocs-material>=9.5.32", "mkdocstrings[python]>=0.25.2"]
